[package]
name = "cnft-forge"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["secrets", "json"] }
blockfrost = "0.2.0"
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread"] }
hex = "0.3.1"
regex = "1"
